#include "UI/ChatWidget.h"
#include "Components/EditableTextBox.h"
#include "Components/TextBlock.h"
#include "Components/VerticalBox.h"
#include "Player/BaseballController.h"

void UChatWidget::NativeConstruct()
{
	Super::NativeConstruct();

	if (ChatInputBox)
	{
		ChatInputBox->OnTextCommitted.AddDynamic(this, &UChatWidget::OnTextCommitted);
	}
}

void UChatWidget::OnTextCommitted(const FText& Text, ETextCommit::Type CommitMethod)
{
	if (CommitMethod == ETextCommit::Type::OnEnter && !Text.IsEmpty())
	{
		ABaseballController* Controller = Cast<ABaseballController>(GetOwningPlayer());
		if (Controller)
		{
			UE_LOG(LogTemp, Warning, TEXT("ğŸ“© í´ë¼ì´ì–¸íŠ¸ì—ì„œ ì„œë²„ë¡œ ë©”ì‹œì§€ ì „ì†¡: %s"), *Text.ToString());
			Controller->ServerSendMessage(Text.ToString());  // âœ… ì—¬ê¸°ì„œ ì„œë²„ RPC í˜¸ì¶œ!
		}

		ChatInputBox->SetText(FText::GetEmpty());
	}
}

void UChatWidget::UpdateChat(const FString& Message)
{
	UE_LOG(LogTemp, Log, TEXT("Sent Message: %s"), *Message);
	
	if (!ChatLogBox) return;

	UTextBlock* NewMessage = NewObject<UTextBlock>(this);
	if (NewMessage)
	{
		NewMessage->SetText(FText::FromString(Message));
		ChatLogBox->AddChild(NewMessage);
		UE_LOG(LogTemp, Display, TEXT("âœ… UIì— ë©”ì‹œì§€ ì¶”ê°€: %s"), *Message);
	}
}

void UChatWidget::SendMessageToServer_Implementation(const FString& Message)
{
}