#include "Player/BaseballController.h"
#include "Blueprint/UserWidget.h"
#include "GameFramework/GameStateBase.h"
#include "System/BaseballGameMode.h"
#include "UI/ChatWidget.h"

void ABaseballController::BeginPlay()
{
	Super::BeginPlay();
	SetInputMode(FInputModeGameAndUI());
	bShowMouseCursor = true;

	if (!IsLocalController())
	{
		UE_LOG(LogTemp, Warning, TEXT("âŒ ë¡œì»¬ ì»¨íŠ¸ë¡¤ëŸ¬ê°€ ì•„ë‹˜, UI ìƒì„± ì•ˆ í•¨"));
		return;
	}
	
	FString AssignedID = HasAuthority() ? TEXT("Host") : TEXT("Guest");

	UE_LOG(LogTemp, Warning, TEXT("ğŸ­ í”Œë ˆì´ì–´ ID í• ë‹¹ (í´ë¼ì´ì–¸íŠ¸ì—ì„œ íŒë³„): %s"), *AssignedID);

	OnLoginWithID(AssignedID);

	ChatWidget = CreateWidget<UChatWidget>(this, ChatWidgetClass);
	if (ChatWidget)
	{
		ChatWidget->AddToViewport();
	}

	UE_LOG(LogTemp, Warning, TEXT("í˜„ì¬ í”Œë ˆì´ì–´ ìˆ˜: %d"), GetWorld()->GetGameState<AGameStateBase>()->PlayerArray.Num());
}

// ì„œë²„ì—ì„œ ë©”ì„¸ì§€ ì²˜ë¦¬ í›„ GameModeì— ì „ë‹¬
void ABaseballController::ServerSendMessage_Implementation(const FString& Message)
{
	TObjectPtr<ABaseballGameMode> GameMode = GetWorld()->GetAuthGameMode<ABaseballGameMode>();
	if (GameMode)
	{
		GameMode->BroadcastMessage(PlayerID, Message);
	}
}

// ì„œë²„ RPC ê²€ì¦ (í•„ìˆ˜)
bool ABaseballController::ServerSendMessage_Validate(const FString& Message)
{
	return !Message.IsEmpty();
}

// í´ë¼ì´ì–¸íŠ¸ ë©”ì„¸ì§€ ìˆ˜ì‹ 
void ABaseballController::ClientReceiveMessage_Implementation(const FString& Message)
{
	UE_LOG(LogTemp, Display, TEXT("ğŸ“¥ í´ë¼ì´ì–¸íŠ¸ì—ì„œ ë©”ì‹œì§€ ìˆ˜ì‹ : %s"), *Message);

	if (ChatWidget)
	{
		ChatWidget->UpdateChat(Message);
	}
}

// ì„œë²„ì—ì„œ í”Œë ˆì´ì–´ ë¡œê·¸ì¸ ì²˜ë¦¬
void ABaseballController::OnLoginWithID_Implementation(const FString& UserID)
{
	UE_LOG(LogTemp, Warning, TEXT("ğŸ“© ì„œë²„ì—ì„œ ë°›ì€ UserID: %s"), *UserID);

	if (UserID.IsEmpty())
	{
		UE_LOG(LogTemp, Error, TEXT("ğŸš¨ UserIDê°€ ë¹„ì–´ ìˆìŒ!"));
		return;
	}
	
	PlayerID = UserID;
}

bool ABaseballController::OnLoginWithID_Validate(const FString& UserID)
{
	return !UserID.IsEmpty();
}