#include "System/MultiBaseballGameState.h"
#include "Net/UnrealNetwork.h"
#include "Player/MultiBaseballController.h"


AMultiBaseballGameState::AMultiBaseballGameState()
	: TargetNumber("")
	, RemainingTime(60)
	, PlayerTurnID("None")
{
	
}

void AMultiBaseballGameState::BroadcastGameReset_Implementation()
{
	UE_LOG(LogTemp, Warning, TEXT("ğŸ‰ TargetNumber ì´ˆê¸° ê°’: %d"), FCString::Atoi(*TargetNumber));
	if (HasAuthority())
	{
		GetWorldTimerManager().ClearTimer(TurnTimerHandle);
		StartTurnTimer();
		
		CreateRandomTargetNumber();

		for (FConstPlayerControllerIterator PlayerControllerIter = GetWorld()->GetPlayerControllerIterator(); PlayerControllerIter; ++PlayerControllerIter)
		{
			TObjectPtr<AMultiBaseballController> PlayerController = Cast<AMultiBaseballController>(*PlayerControllerIter);
			if (PlayerController)
			{
				PlayerController->ResetLeftChance();
			}
		}
	}
	UE_LOG(LogTemp, Warning, TEXT("ğŸ‰ TargetNumber ì—…ë°ì´íŠ¸ë¨: %d"), FCString::Atoi(*TargetNumber));

	APlayerController* LocalController = GetWorld()->GetFirstPlayerController();
	if (LocalController)
	{
		AMultiBaseballController* PlayerController = Cast<AMultiBaseballController>(LocalController);
		if (PlayerController)
		{
			PlayerController->ClientReceiveGameReset();
		}
	}

	if (HasAuthority())
	{
		PlayerTurnID = "Host";
		BroadcastWhoTurn(PlayerTurnID);
	}
}

void AMultiBaseballGameState::BroadcastLeftChance_Implementation(const FString& SenderName, const int& LeftChance)
{
	if (HasAuthority())
	{
		for (FConstPlayerControllerIterator PlayerControllerIter = GetWorld()->GetPlayerControllerIterator(); PlayerControllerIter; ++PlayerControllerIter)
		{
			TObjectPtr<AMultiBaseballController> PlayerController = Cast<AMultiBaseballController>(*PlayerControllerIter);
			if (PlayerController)
			{
				PlayerController->ClientReceiveLeftTurn(SenderName, LeftChance);
			}
		}
	}
}

void AMultiBaseballGameState::BroadcastOtherWinCount_Implementation(const FString& SenderName, const int& OtherWinCount)
{
	if (HasAuthority())
	{
		for (FConstPlayerControllerIterator PlayerControllerIter = GetWorld()->GetPlayerControllerIterator(); PlayerControllerIter; ++PlayerControllerIter)
		{
			TObjectPtr<AMultiBaseballController> PlayerController = Cast<AMultiBaseballController>(*PlayerControllerIter);
			if (PlayerController)
			{
				PlayerController->ClientReceiveOtherWinCount(SenderName, OtherWinCount);
			}
		}
	}
}

void AMultiBaseballGameState::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const
{
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);

	DOREPLIFETIME(AMultiBaseballGameState, TargetNumber);
	DOREPLIFETIME(AMultiBaseballGameState, RemainingTime);
	DOREPLIFETIME(AMultiBaseballGameState, PlayerTurnID);
}

void AMultiBaseballGameState::BeginPlay()
{
	Super::BeginPlay();
	
	if (HasAuthority())
	{
		CreateRandomTargetNumber();
		StartTurnTimer();
	}
	UE_LOG(LogTemp, Warning, TEXT("ğŸ‰ TargetNumber ì—…ë°ì´íŠ¸ë¨: %d"), FCString::Atoi(*TargetNumber));
}

void AMultiBaseballGameState::CreateRandomTargetNumber()
{
	bool Memo[10] = { false };
	FString TargetNumberString = TEXT("");
    
	while (TargetNumberString.Len() < 3)
	{
		int32 RandomNumber = FMath::RandRange(1, 9);
		if (!Memo[RandomNumber])
		{
			TargetNumberString += FString::FromInt(RandomNumber);
			Memo[RandomNumber] = true;
		}
	}
	TargetNumber = TargetNumberString;
}

void AMultiBaseballGameState::CheckMessage_Implementation(const FString& SenderName, const FString& Message, APlayerController* SenderController)
{
	FString Answer = "";
	FString FullMessage = "";

	EMessage_Type MessageType = CheckMessageType(Message, Answer, SenderController);
	if (EMessage_Type::WrongAnswer == MessageType)
	{		
		FullMessage = FString::Printf(TEXT("[System]: %s"), *Answer);
		
		TObjectPtr<AMultiBaseballController> PlayerController = Cast<AMultiBaseballController>(SenderController);
		if (PlayerController)
		{
			PlayerController->ClientReceiveMessage(SenderName, FullMessage, EMessage_Type::SystemMessage);
		}
	}
	else
	{
		if (EMessage_Type::Answer == MessageType)
		{
			GetWorldTimerManager().ClearTimer(TurnTimerHandle);
			BroadcastMessage(SenderName, Answer);
			if (CheckAnswer(SenderName, Answer)) // ì •ë‹µì„ ë§ì·„ì„ ë–„
			{
				TObjectPtr<AMultiBaseballController> PlayerController = Cast<AMultiBaseballController>(SenderController);
				if (PlayerController)
				{
					PlayerController->PlayerWin();
					BroadcastOtherWinCount(SenderName, PlayerController->GetWinCount());
				}
				
				BroadcastFinishResult(SenderName, "Win!!!");
				return;
			}
			else // ì•„ì§ ì •ë‹µì„ ë§ì¶”ì§€ ëª»í–ˆì„ ë•Œ
			{
				// + í´ë¼ì´ì–¸íŠ¸ íšŸìˆ˜ ì¤„ì´ê¸°
				TObjectPtr<AMultiBaseballController> PlayerController = Cast<AMultiBaseballController>(SenderController);
				if (PlayerController)
				{
					int NewLeftChance = PlayerController->GetLeftChance() - 1;
					PlayerController->SetLeftChance(NewLeftChance);

					FString LeftChanceMessage = FString::Printf(TEXT("%së‹˜ì˜ ë‚¨ì€ íšŸìˆ˜ : %d"), *SenderName, NewLeftChance);
					BroadcastMessage("System", LeftChanceMessage, EMessage_Type::SystemMessage);

					// ë‚¨ì€ í„´ UI ì¶œë ¥
					BroadcastLeftChance(SenderName, NewLeftChance);

					// ë¬´ìŠ¹ë¶€ì¸ì§€ í™•ì¸
					if (IsDraw())
					{
						BroadcastFinishResult("", "Draw!!!");
						return;
					}
				}
			}
			SwitchPlayerTurn();
			StartTurnTimer();
		}
		else
		{
			BroadcastMessage(SenderName, Message);
		}
	}
}

void AMultiBaseballGameState::BroadcastFinishResult_Implementation(const FString& SenderName, const FString& Message)
{
	FString FullMessage = FString::Printf(TEXT("%s %s"), *SenderName, *Message);

	APlayerController* LocalController = GetWorld()->GetFirstPlayerController();
	if (LocalController)
	{
		AMultiBaseballController* PlayerController = Cast<AMultiBaseballController>(LocalController);
		if (PlayerController)
		{
			PlayerController->ClientReceiveFinishResult(FullMessage);
			// UI ë„ìš°ê¸°
			PlayerController->ClientReceiveTargetNum(TargetNumber);
		}
	}
}

void AMultiBaseballGameState::BroadcastMessage_Implementation(const FString& SenderName, const FString& Message, EMessage_Type MessageType)
{
	FString FullMessage = FString::Printf(TEXT("[%s]: %s"), *SenderName, *Message);

	APlayerController* LocalController = GetWorld()->GetFirstPlayerController();
	if (LocalController)
	{
		AMultiBaseballController* PlayerController = Cast<AMultiBaseballController>(LocalController);
		if (PlayerController)
		{
			PlayerController->ClientReceiveMessage(SenderName, FullMessage, MessageType);
		}
	}
}

EMessage_Type AMultiBaseballGameState::CheckMessageType(const FString& Message, FString& Answer, APlayerController* SenderController)
{
	Answer = TEXT("");
	if (!Message.IsEmpty())
	{
		if (Message[0] == '/')
		{
			if (TObjectPtr<AMultiBaseballController> PlayerController = Cast<AMultiBaseballController>(SenderController))
			{
				if (PlayerTurnID == PlayerController->GetPlayerID())
				{
					if (PlayerController->GetLeftChance() > 0)
					{
						if (Message.Len() == 4)
						{
							Answer = Message.Mid(1, 4);
							return EMessage_Type::Answer;
						}
						else
						{
							Answer = TEXT("ì˜ëª»ëœ ëª…ë ¹ì–´ ì…ë‹ˆë‹¤.");
							return EMessage_Type::WrongAnswer;
						}
					}
					else
					{
						Answer = TEXT("í”Œë ˆì´ì–´ì˜ ë‚¨ì€ íšŸìˆ˜ê°€ ë¶€ì¡±í•©ë‹ˆë‹¤.");
						return EMessage_Type::WrongAnswer;
					}
				}
				else
				{
					Answer = TEXT("í”Œë ˆì´ì–´ì˜ ì°¨ë¡€ê°€ ì•„ë‹™ë‹ˆë‹¤.");
					return EMessage_Type::WrongAnswer;
				}
			}
		}
	}

	Answer = Message;
	return EMessage_Type::Message;
}

bool AMultiBaseballGameState::CheckAnswer(const FString& SenderName, const FString& Answer)
{
	bool Is_Correct = false;
	int StrikeNum = 0, BallNum = 0, OutNum = 0;
	
	for (int i = 0; i < Answer.Len(); ++i)
	{
		int FoundIndex;
		if (!TargetNumber.FindChar(Answer[i], FoundIndex))
		{
			OutNum++;
		}
		else
		{
			if (FoundIndex == i)
			{
				StrikeNum++;
			}
			else
			{
				BallNum++;
			}
		}
	}

	if (StrikeNum == 3)
	{
		Is_Correct = true;
	}
	
	FString Message = FString::Printf(TEXT("%sì˜ ê²°ê³¼ [S : %d B : %d Out : %d]"), *SenderName, StrikeNum, BallNum, OutNum);
	BroadcastMessage("System", Message, EMessage_Type::SystemMessage);
	BroadcastSBOResult(SenderName, Answer, StrikeNum, BallNum, OutNum);
	return Is_Correct;
}

void AMultiBaseballGameState::BroadcastSBOResult_Implementation(const FString& SenderName, const FString& Answer, int StrikeNum, int BallNum, int OutNum)
{
	APlayerController* LocalController = GetWorld()->GetFirstPlayerController();
	if (LocalController)
	{
		AMultiBaseballController* PlayerController = Cast<AMultiBaseballController>(LocalController);
		if (PlayerController)
		{
			PlayerController->ClientReceiveSBO(SenderName, Answer, StrikeNum, BallNum, OutNum);
		}
	}
}

bool AMultiBaseballGameState::IsDraw()
{
	bool Result = true;
	for (FConstPlayerControllerIterator PlayerControllerIter = GetWorld()->GetPlayerControllerIterator(); PlayerControllerIter; ++PlayerControllerIter)
	{
		TObjectPtr<AMultiBaseballController> PlayerController = Cast<AMultiBaseballController>(*PlayerControllerIter);
		if (PlayerController)
		{
			if (PlayerController->GetLeftChance() > 0)
			{
				Result = false;
				break;
			}
		}
	}

	return Result;
}

void AMultiBaseballGameState::StartTurnTimer()
{
	RemainingTime = 60; // í„´ì´ ì‹œì‘ë  ë•Œ 60ì´ˆë¡œ ì´ˆê¸°í™”
	GetWorldTimerManager().SetTimer(TurnTimerHandle, this, &AMultiBaseballGameState::UpdateTurnTimer, 1.0f, true);

	if (HasAuthority())
	{
		APlayerController* LocalController = GetWorld()->GetFirstPlayerController();
		if (LocalController)
		{
			AMultiBaseballController* PlayerController = Cast<AMultiBaseballController>(LocalController);
			if (PlayerController)
			{
				PlayerController->ClientReceiveTimerText();
			}
		}
	}
}

void AMultiBaseballGameState::UpdateTurnTimer()
{
	if (RemainingTime > 0)
	{
		RemainingTime--;

		APlayerController* LocalController = GetWorld()->GetFirstPlayerController();
		if (LocalController)
		{
			AMultiBaseballController* PlayerController = Cast<AMultiBaseballController>(LocalController);
			if (PlayerController)
			{
				PlayerController->ClientReceiveTimerText();
			}
		}
	}
	else
	{
		GetWorldTimerManager().ClearTimer(TurnTimerHandle);
		
		for (FConstPlayerControllerIterator PlayerControllerIter = GetWorld()->GetPlayerControllerIterator(); PlayerControllerIter; ++PlayerControllerIter)
		{
			TObjectPtr<AMultiBaseballController> PlayerController = Cast<AMultiBaseballController>(*PlayerControllerIter);
			if (PlayerController->GetPlayerID() == PlayerTurnID)
			{
				int NewLeftChance = PlayerController->GetLeftChance() - 1;
				PlayerController->SetLeftChance(NewLeftChance);

				FString LeftChanceMessage = FString::Printf(TEXT("%së‹˜ì˜ ë‚¨ì€ íšŸìˆ˜ : %d"), *PlayerTurnID, NewLeftChance);
				BroadcastMessage("System", LeftChanceMessage, EMessage_Type::SystemMessage);

				// ë‚¨ì€ í„´ UI ì¶œë ¥
				BroadcastLeftChance(PlayerTurnID, NewLeftChance);
				
				// ë¬´ìŠ¹ë¶€ì¸ì§€ í™•ì¸
				if (IsDraw())
				{
					BroadcastFinishResult("", "Draw!!!");
					return;
				}
			}
		}

		SwitchPlayerTurn();
		StartTurnTimer();
	}
}

void AMultiBaseballGameState::OnRep_RemainTime()
{
	APlayerController* LocalController = GetWorld()->GetFirstPlayerController();
	if (LocalController)
	{
		AMultiBaseballController* PlayerController = Cast<AMultiBaseballController>(LocalController);
		if (PlayerController)
		{
			PlayerController->ClientReceiveTimerText();
		}
	}
}

void AMultiBaseballGameState::SwitchPlayerTurn()
{
	if (PlayerTurnID == "Host")
	{
		PlayerTurnID = "Guest";
	}
	else
	{
		PlayerTurnID = "Host";
	}
	BroadcastWhoTurn(PlayerTurnID);
}

void AMultiBaseballGameState::BroadcastWhoTurn_Implementation(const FString& InPlayerTurnID)
{
	APlayerController* LocalController = GetWorld()->GetFirstPlayerController();
	if (LocalController)
	{
		AMultiBaseballController* PlayerController = Cast<AMultiBaseballController>(LocalController);
		if (PlayerController)
		{
			PlayerController->ClientReceiveWhoTurn(InPlayerTurnID);
		}
	}
}